name: fwallet
description: A new project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  tron_dart:
    path: ../tron/tron_dart

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.0
  ai_barcode_scanner: ^5.1.1+2
  qr_flutter: ^4.1.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.3
  install_plugin: ^2.1.0
  path_provider: ^2.1.1
  dio: ^5.3.3
  permission_handler: ^11.0.1
  get_it: ^7.6.4
  logger: ^2.0.2+1
  reorderables: ^0.6.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  # webview_flutter: ^4.4.2
  walletconnect_flutter_v2: ^2.2.3
  encrypt: ^5.0.3
  blockchain_utils: ^3.2.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0
  desktop_webview_window: ^0.2.3
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  flutter_riverpod: ^2.5.1
  qr_code_scanner: ^1.0.1
  web3dart: ^2.7.3
  http: ^1.2.2
  sqflite_common_ffi: ^2.3.3
  bitcoin_base: ^4.7.0
  # solana: ^0.30.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/ic_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - images/

  generate: true
